export enum Secrets {
  ENV = 'NODE_ENV',
  PORT = 'PORT',
  HOST = 'HOST',
  ORIGIN = 'ORIGIN',
  CREDENTIALS = 'CREDENTIALS',
  MONGO_HOST = 'MONGO_HOST',
  MONGO_PORT = 'MONGO_PORT',
  REDIS_URL = 'REDIS_URL',
  MONGO_USER = 'MONGO_INITDB_ROOT_USERNAME',
  MONGO_PASSWORD = 'MONGO_INITDB_ROOT_PASSWORD',
}
